### ISSUE TITLE
generate gif

### ISSUE THREAD

**Issue by whenflyfish** [autonomousvision/king#1]
Thank you for releasing this project.
But how should I generate the gif in your home page from the generation_results/scenario_records.json.
Thank you very much.

**Comment by lasnik** [comment]
Hi! Generating a .gif exactly as the teaser on the landing page of this repository is a bit involved. However, you can use `python tools/visualize_scenarios.py`,  which is a lightweight script that draws .gifs of the generated scenarios in a simple BEV representation. This is also what we used during development for this project.

To use it, you need to spin up a CARLA server in the background. Make sure the argument `--scenario_log_dir`  points to the directory where your generation results are located. Additionally you may need to set the environment variables for CARLA's python API as in `run_generation.sh` (l.3-7).

**Comment by whenflyfish** [comment]
Okay I got it. Thank you for your reply!
