### ISSUE TITLE
How can I generate the data?

### ISSUE THREAD

**Issue by raozhongyu** [autonomousvision/king#2]
Thanks for your great work. I have generate the Scenarios by run bash run_generation_both_paths.sh. I 'd like to generate the sensor and expert data. Could you give me some suggestions?

**Comment by lasnik** [comment]
Hi @raozhongyu!

You can use [this script](https://github.com/autonomousvision/king/blob/6acd2154cd689b3121664e60760378ba484659c6/driving_agents/king/aim_bev/robust_train.py) as a reference. It automatically collects data from critical scenarios.

**Comment by raozhongyu** [comment]
Thanks a lot

**Comment by raozhongyu** [comment]
Hi, I want collect the data including the rgb and lidar. In this way, I change the renderer_class to CALTLA. But, I meet some question 
1、WARNING: Could not spawn ego agent.
WARNING: Could not spawn adv agent 0.
WARNING: Could not spawn adv agent 1.
WARNING: Could not spawn adv agent 2.

2、the rgb image seems only have two channels?

can you give me some suggestions?

**Comment by raozhongyu** [comment]
I have solve the second question, but the camera may loss sometimes.

**Comment by lasnik** [comment]
Hi, glad you have solved the second issue. 

As for the first one, that warning means the CARLA server was unable spawn the actor at the specified location (e.g. due to physics). This should only happen very rarely. If you encounter it frequently, there may be a misconfiguration problem. You could try visualizing the locations where the renderer is trying to spawn these agents in CARLA to figure out potential issues.

**Comment by raozhongyu** [comment]
Thanks a lot。 I will try it



发自我的iPhone


------------------ Original ------------------
From: lasnik ***@***.***&gt;
Date: Thu,Jun 1,2023 5:29 PM
To: autonomousvision/king ***@***.***&gt;
Cc: raozhongyu ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [autonomousvision/king] How can I generate the data? (Issue #2)





 
Hi, glad you have solved the second issue.
 
As for the first one, that warning means the CARLA server was unable spawn the actor at the specified location (e.g. due to physics). This should only happen very rarely. If you encounter it frequently, there may be a misconfiguration problem. You could try visualizing the locations where the renderer is trying to spawn these agents in CARLA to figure out potential issues.

**Comment by raozhongyu** [comment]
Sorry to bother you.  I find that the WARNING: Could not spawn ego agent happen every time when I choose the rende_classes as CARLA. If I chose the render_classes as STN, it goes well.

**Comment by raozhongyu** [comment]
I check the code and find that there may be something wrong with ego_State with Carla render :
The ego_state is shown as {'pos': tensor([[[ 121.8334, -201.4548]]], device='cuda:0'), 'vel': tensor([[[-3.9988, -0.0989]]], device='cuda:0'), 'yaw': tensor([[[-3.1167]]], device='cuda:0')} which seems wrong.

**Comment by raozhongyu** [comment]
I find the reson may be our scenarios are generated based on the AIM-BEV.  I try to change the way to transfuser

**Comment by lasnik** [comment]
The STN renderer does not use the CARLA rendering engine and hence does not need to spawn actors in the server.

In principle this should also work for scenarios generated based on AIM-BEV and the ego_state you showed seems fine on first glance.

As mentioned above, I suggest to use [CARLA's debug functionality](https://carla.readthedocs.io/en/0.9.10/python_api/#carla.DebugHelper) to visualize potential issues with these spawning locations in the CARLA server.

**Comment by raozhongyu** [comment]
Thanks a lot. I will try it.
