### ISSUE TITLE
ModuleNotFoundError: No module named 'agents.navigation.global_route_planner_dao'

### ISSUE THREAD

**Issue by zhouyu102030** [autonomousvision/king#4]
Hello, I'm reaching out to inquire about the issue I'm encountering with the "bash run_generation_transfuser.sh" command. It appears to be unable to locate "agencies.navigation.global_route_planner_dao." Can you please provide guidance on how to resolve this issue and get the program functioning correctly? Your response would be greatly appreciated. Thank you!
![2023-10-31 21-39-30屏幕截图](https://github.com/autonomousvision/king/assets/85484578/76f80e46-45e9-48a8-aa0f-c86ec3e69712)

**Comment by Dengdengdengd** [comment]
请问楼主解决了吗
