### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'sampling_resolution'

### ISSUE THREAD

**Issue by zhouyu102030** [autonomousvision/king#5]
When executing the 'bash run_generation_transfuser.sh' command, the following error was reported:
![image](https://github.com/autonomousvision/king/assets/85484578/438ed483-1a36-4b1a-b10e-7e26403c41d8)
I would appreciate guidance on resolving this error. Thank you for your prompt response!

**Comment by lasnik** [comment]
Hi,

it looks like this is a mismatch in the CARLA version expected by the scenario_runner/leaderboard and the version you are using. For KING, we used CARLA 0.9.10.1. Are you using a newer version by chance?
